#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

java -cp "$SCRIPTPATH/hackass.jar:/usr/local/lib/antlr-complete.jar" org.antlr.v4.gui.TestRig hackass.grammar.Hackass file $* -gui
